---
title: Getting Started With Sonic Pi
hero_image: images/banner.png
description: Learn how to live code music on the Raspberry Pi with Sonic Pi
original_url: https://raspberrypi.org/learning/getting-started-with-sonic-pi
theme: red
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Taking Sonic Pi Further
- title: Adding effects
- title: Modifying Parameters
- title: Using rrand
- title: What next?
- title: Getting started with Sonic Pi 2
- title: First sounds with Sonic Pi
- title: Loop a tune
- title: MIDI notes and music notes
- title: Change the sounds
- title: Use samples
- title: Playing two tunes at the same time
- title: Live code!
- title: What next?

